#!/bin/sh
# Start/Stop script for lifxdimmer
LOCKFILE="/apps/lifxdimmer/lifxdimmer.lock"
case $1 in
    start|forcestart)
				if [ -e $LOCKFILE ]; then 
					# check if script already running
					PID=`cat $LOCKFILE`
					if [ -e /proc/${PID} -a /proc/${PID}/exe ]; then
						echo "Service already running."
					else
						echo "Starting service."
						lifxdimmer > /dev/null 2>&1 &
					fi
				else
					echo "Starting service."
					lifxdimmer > /dev/null 2>&1 &
				fi
                ;;
        stop)
				if [ -e $LOCKFILE ] ; then
					echo "Stopping service."
					kill -15 $(cat $LOCKFILE)
					rm $LOCKFILE
				else
					echo "Service not running."
				fi
                ;;
        restart)
                $0 stop
                $0 start
        ;;
        status)
				if [ -e $LOCKFILE ] ; then
					PID=`cat $LOCKFILE`
					if [ -e /proc/${PID} -a /proc/${PID}/exe ]; then
						echo "Service running."
					else
						echo "Service stopped."
					fi
				else
					echo "Service stopped."
				fi
        ;;
esac